-- Database, schema, warehouse, and role scaffolding for the fraud platform EDW.

CREATE DATABASE IF NOT EXISTS FRAUD_PLATFORM;

CREATE SCHEMA IF NOT EXISTS FRAUD_PLATFORM.RAW;
CREATE SCHEMA IF NOT EXISTS FRAUD_PLATFORM.STAGING;
CREATE SCHEMA IF NOT EXISTS FRAUD_PLATFORM.MARTS;

CREATE WAREHOUSE IF NOT EXISTS WH_LOADER
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYTICS
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- RBAC: separate load vs. read-only vs. fraud-ops access.
CREATE ROLE IF NOT EXISTS PIPELINE_LOADER;
CREATE ROLE IF NOT EXISTS ANALYST_RO;
CREATE ROLE IF NOT EXISTS FRAUD_OPS;

GRANT USAGE ON DATABASE FRAUD_PLATFORM TO ROLE PIPELINE_LOADER, ANALYST_RO, FRAUD_OPS;
GRANT USAGE ON WAREHOUSE WH_LOADER TO ROLE PIPELINE_LOADER;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ANALYST_RO, FRAUD_OPS;

GRANT ALL ON SCHEMA FRAUD_PLATFORM.RAW TO ROLE PIPELINE_LOADER;
GRANT ALL ON SCHEMA FRAUD_PLATFORM.STAGING TO ROLE PIPELINE_LOADER;
GRANT ALL ON SCHEMA FRAUD_PLATFORM.MARTS TO ROLE PIPELINE_LOADER;

GRANT USAGE ON SCHEMA FRAUD_PLATFORM.MARTS TO ROLE ANALYST_RO, FRAUD_OPS;
GRANT SELECT ON ALL TABLES IN SCHEMA FRAUD_PLATFORM.MARTS TO ROLE ANALYST_RO, FRAUD_OPS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRAUD_PLATFORM.MARTS TO ROLE ANALYST_RO, FRAUD_OPS;
