-- STAGING schema: deduped/conformed views + Streams for CDC-style incremental loads
-- into MARTS.

USE SCHEMA FRAUD_PLATFORM.STAGING;

CREATE STREAM IF NOT EXISTS STRM_RAW_TRANSACTIONS
  ON TABLE FRAUD_PLATFORM.RAW.RAW_TRANSACTIONS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_RAW_FRAUD_FEATURES
  ON TABLE FRAUD_PLATFORM.RAW.RAW_FRAUD_FEATURES
  APPEND_ONLY = TRUE;

CREATE VIEW IF NOT EXISTS VW_TRANSACTIONS_DEDUPED AS
SELECT *
FROM (
  SELECT
    t.*,
    ROW_NUMBER() OVER (PARTITION BY transaction_id ORDER BY _loaded_at DESC) AS rn
  FROM FRAUD_PLATFORM.RAW.RAW_TRANSACTIONS t
)
WHERE rn = 1;
