# Databricks notebook source
# MAGIC %md
# MAGIC # 04 — Fraud Feature Engineering (Free Edition practice version)
# MAGIC Reuses `databricks/src/transformations/fraud_features.py` unchanged — the same
# MAGIC velocity/geo/device/merchant-risk feature logic as the main pipeline — writing to
# MAGIC a Unity Catalog managed table. The merchant risk lookup is read from the `raw`
# MAGIC volume CSV generated by `scripts/generate_synthetic_data.py`.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Repos/fraud-platform/databricks/src")

from transformations.fraud_features import build_fraud_feature_set

dbutils.widgets.text("catalog", "main")
dbutils.widgets.text("schema", "fraud_platform")

catalog = dbutils.widgets.get("catalog")
schema = dbutils.widgets.get("schema")
raw_volume = f"/Volumes/{catalog}/{schema}/raw"

# COMMAND ----------

silver_txns = spark.table(f"{catalog}.{schema}.silver_transactions")

merchant_risk_lookup = (
    spark.read.option("header", True)
    .option("inferSchema", True)
    .csv(f"{raw_volume}/merchant_risk_lookup")
)

feature_df = build_fraud_feature_set(silver_txns, merchant_risk_lookup)

# COMMAND ----------

feature_df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
    f"{catalog}.{schema}.gold_fraud_features"
)

print(f"gold_fraud_features written: {feature_df.count()} rows")
display(
    spark.table(f"{catalog}.{schema}.gold_fraud_features")
    .select(
        "transaction_id",
        "account_id",
        "txn_count_1h",
        "txn_count_24h",
        "is_impossible_travel",
        "distinct_accounts_per_device_24h",
        "merchant_risk_score",
    )
    .orderBy("transaction_ts")
    .limit(20)
)

# COMMAND ----------

# MAGIC %md
# MAGIC This is the feature set `ml/src/train.py` expects (see `FEATURE_COLUMNS` in
# MAGIC `ml/src/feature_store.py`). A good screenshot/demo moment: filter this table for
# MAGIC `is_impossible_travel = true` or a high `distinct_accounts_per_device_24h` to show
# MAGIC the fraud signals firing on the synthetic data.
