-- Snowpipe: auto-ingest new Gold Delta/Parquet files landing in ADLS Gen2 into
-- RAW.RAW_TRANSACTIONS as soon as Databricks writes them (event-driven via
-- Azure Event Grid notification integration).

USE SCHEMA FRAUD_PLATFORM.RAW;

CREATE NOTIFICATION INTEGRATION IF NOT EXISTS ADLS_EVENT_GRID_INT
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://stfraudplatformprod.queue.core.windows.net/snowpipe-events'
  AZURE_TENANT_ID = '<azure_tenant_id>';

CREATE PIPE IF NOT EXISTS PIPE_RAW_TRANSACTIONS
  AUTO_INGEST = TRUE
  INTEGRATION = 'ADLS_EVENT_GRID_INT'
AS
COPY INTO RAW_TRANSACTIONS
FROM @STG_CURATED_GOLD/transactions/
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

CREATE PIPE IF NOT EXISTS PIPE_RAW_FRAUD_FEATURES
  AUTO_INGEST = TRUE
  INTEGRATION = 'ADLS_EVENT_GRID_INT'
AS
COPY INTO RAW_FRAUD_FEATURES
FROM @STG_CURATED_GOLD/fraud_features/
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

-- ALTER PIPE ... REFRESH; -- manual backfill if Event Grid misses a notification
